# header: timestamp (builtin_interfaces/Time) and frame_id (string)
std_msgs/Header header

# hand: left or right
string side

# mediapipe defined fingers
float32 confidence

# 0 = wrist
# 1 = thumb_cmc
# 2 = thumb_mcp
# 3 = thumb_ip
# 4 = thumb_tip
# 5 = index_finger_mcp
# 6 = index_finger_pip
# 7 = index_finger_dip
# 8 = index_finger_tip
# 9 = middle_finger_mcp
# 10 = middle_finger_pip
# 11 = middle_finger_dip
# 12 = middle_finger_tip
# 13 = ring_finger_mcp
# 14 = ring_finger_pip
# 15 = ring_finger_dip
# 16 = ring_finger_tip
# 17 = pinky_mcp
# 18 = pinky_pip
# 19 = pinky_dip
# 20 = pinky_tip
geometry_msgs/Point32[20] fingers
