services:
  # base profile
  base: &base
    command: bash
    tty: true
    stdin_open: true
    stop_grace_period: 5s # before SIGKILL

  # base docker
  # docker nodes are mostly for jetson support
  base_docker: &base_docker
    <<: *base
    network_mode: host

  # base podman
  # this is used on my Fedora desktop
  base_podman: &base_podman
    <<: *base
    network_mode: pasta
    security_opt:
      - label=type:container_runtime_t

  # base gui dev
  # this is used on the desktop for gui applications
  base_gui: &base_gui
    <<: *base_podman
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

  # base nvidia
  # TODO: rework this after Podman 5.4.0
  # Introduce separate profiles:
  # - Jetson
  # - Podman
  base_nvidia:
    <<: *base_docker
    runtime: nvidia
