services:
  # base
  base: &base
    profiles:
      - null_profile
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_gui

  base_nvidia: &base_nvidia
    profiles:
      - null_profile
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_nvidia

  # latest ros dev container
  ros_dev: &ros_dev
    <<: *base
    profiles:
      - dev
    image: ghcr.io/amidg/ros2_controls_dev:latest
    container_name: ros_dev
    network_mode: host
    environment:
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    volumes:
      - ./:/app/src:z

  # hardware demo container
  # NOTE (Dmitrii):
  # Due to the Podman group management, running hardware from podman
  # is not supported until further notice. USE DOCKER
  # This configuration works with `sudo podman`
  # but it kinda defeats the purpose
  # Podman to Docker networking requires FastDDS to use the following:
  # https://github.com/eProsima/Fast-DDS/issues/5396#issuecomment-2493358758
  # export FASTDDS_BUILTIN_TRANSPORTS=UDPv4
  hardware_dev: &hardware_dev
    profiles:
      - hardware_dev
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_security
    image: ghcr.io/amidg/ros2_controls_dev:latest
    container_name: hardware_dev
    network_mode: host
    environment:
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    privileged: true
    volumes:
      - ./:/app/src:z

  # lilpleb robot
  lilpleb_hardware:
    <<: *hardware_dev
    profiles:
      - lilpleb
    container_name: lilpleb_hardware_demo
    devices:
      - /dev/ttyUSB0
