services:
  # lilpleb controls container
  lilpleb_create_node:
    profiles:
      - lilpleb
    extends:
      file: base.yaml
      service: base_nvidia
    build:
      context: ./3rdparty
      dockerfile: Dockerfile.create
      target: base
    container_name: lilpleb_create_node
    privileged: true
    volumes:
      # ros packages
      - ./3rdparty/create_robot:/app/src/create_robot
      - ./3rdparty/libcreate:/app/src/libcreate
      # for the tty access
      - /dev:/dev

  # robotics simulation container
  lilpleb_simulation:
    profiles:
      - lilpleb_sim
    extends:
      file: base.yaml
      service: base_gui
    image: ghcr.io/amidg/ros2:latest
    container_name: lilpleb_simulation
    devices:
      - /dev/input/js0
    annotations:
      - run.oci.keep_original_groups=1
    volumes:
      # ros packages
      #- ./3rdparty/joystick:/app/src/joystick:ro
      - ./:/app/src:z
