services:
  # lilpleb controls container
  # designed to run on the Jetson Xavier NX
  lilpleb_create_node:
    profiles:
      - lilpleb
    build:
      context: ./3rdparty
      dockerfile: Dockerfile.create
      target: base
    container_name: lilpleb_create_node
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - ./3rdparty/create_robot:/create_ws/src/create_robot
      - ./3rdparty/libcreate:/create_ws/src/libcreate
      # for the tty access
      - /dev:/dev
    stdin_open: true
    tty: true
