services:
  # base jetson container
  base_nvidia: &base_nvidia
    profiles:
      - null_nvidia
    runtime: nvidia
    tty: true
    stdin_open: true

  # lilpleb controls container
  # designed to run on the Jetson Xavier NX
  lilpleb_create_node:
    <<: *base_nvidia
    profiles:
      - lilpleb
    build:
      context: ./3rdparty
      dockerfile: Dockerfile.create
      target: base
    container_name: lilpleb_create_node
    privileged: true
    network_mode: host
    volumes:
      - ./3rdparty/create_robot:/app/src/create_robot
      - ./3rdparty/libcreate:/app/src/libcreate
      # for the tty access
      - /dev:/dev
