services:
  # base
  base: &base
    profiles:
      - null_profile
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_gui

  base_nvidia: &base_nvidia
    profiles:
      - null_profile
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_nvidia

  # latest ros dev container
  ros_dev: &ros_dev
    <<: *base
    profiles:
      - ros_dev
    image: ghcr.io/amidg/ros2:latest
    container_name: ros_dev
    volumes:
      - ./:/app/src:z

  # latest gazebo container
  gazebo_dev: &gazebo_dev
    <<: *base
    profiles:
      - gazebo_dev
    image: gazebo:gzserver11
    container_name: gazebo_dev
    volumes:
      - ./:/app/src:z

  # container for demo packages
  ros_demo: &ros_demo
    <<: *base
    profiles:
      - demo
    image: ghcr.io/amidg/ros2:latest
    container_name: ros_demo
    volumes:
      - ./demo:/app/src:z

  # lilpleb controls container
  # NOTE (Dmitrii):
  # This is podman version, must be started with `podman-compose`
  # if started with `podman compose` that executes `docker compose`
  # it will break
  # TODO (Dmitrii):
  # Rewrite this using docker only because no podman on Nvidia Jetson
  lilpleb_hardware_demo:
    profiles:
      - lilpleb_desktop
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_gui
      #service: base_security
    image: ghcr.io/amidg/ros2:latest
    # TODO (Dmitrii): fix networking for podman VS docker
    container_name: lilpleb_hardware_demo
    #privileged: true
    group_add:
      - keep-groups
    devices:
      - /dev/ttyUSB0
    volumes:
      # for the tty access
      #- /dev:/dev
      # packages
      - ./:/app/src:z

  # lilpleb controls container
  lilpleb_create_node:
    <<: *base_nvidia
    profiles:
      - lilpleb
    build:
      context: ./containers
      dockerfile: Dockerfile.create
      target: base
    container_name: lilpleb_create_node
    privileged: true
    volumes:
      # ros packages
      - ./3rdparty/create_robot:/app/src/create_robot
      - ./3rdparty/libcreate:/app/src/libcreate
      # for the tty access
      - /dev:/dev
