services:
  # base
  base: &base
    profiles:
      - null_profile
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_gui

  base_nvidia: &base_nvidia
    profiles:
      - null_profile
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_nvidia

  # latest ros dev container
  ros_dev: &ros_dev
    <<: *base
    profiles:
      - ros_dev
    image: ghcr.io/amidg/ros2:latest
    container_name: ros_dev
    volumes:
      - ./:/app/src:z

  # latest gazebo container
  gazebo_dev: &gazebo_dev
    <<: *base
    profiles:
      - gazebo_dev
    image: gazebo:gzserver11
    container_name: gazebo_dev
    volumes:
      - ./:/app/src:z

  # container for demo packages
  ros_demo: &ros_demo
    <<: *base
    profiles:
      - demo
    image: ghcr.io/amidg/ros2:latest
    container_name: ros_demo
    volumes:
      - ./demo:/app/src:z

  # NOTE (Dmitrii):
  # Due to the Podman group management, running hardware from podman
  # is not supported until further notice. USE DOCKER
  #
  # This configuration works with `sudo podman`
  # but it kinda defeats the purpose
  lilpleb_hardware:
    profiles:
      - lilpleb
    extends:
      file: ./containers/dockerfiles/base.yml
      service: base_security
    image: ghcr.io/amidg/ros2:latest
    container_name: lilpleb_hardware_demo
    devices:
      - /dev/ttyUSB0
    volumes:
      - ./:/app/src:z
