controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    # Global controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # drivetrain controller
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    # LED/Buttons controller
    gpio_controller:
      type: gpio_controllers/GpioCommandController

# diff robot controllers
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.235
    wheel_radius: 0.036

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

gpio_controller:
  ros__parameters:
    gpios:
      - status_leds
      - buttons
      - bumper_light_sensors_static
      - bumper_light_sensors_bool
      - bumper_light_sensors_raw
      - battery
      - cliff
      - wheeldrop
    command_interfaces:
      status_leds:
        - interfaces:
          - debris_led
          - spot_led
          - dock_led
          - check_led
          - power_led
    state_interfaces:
      buttons:
        - interfaces:
          - clean_button
          - clock_button
          - schedule_button
          - day_button
          - hour_button
          - minute_button
          - dock_button
          - spot_button
      bumper_light_sensors_static:
        - interfaces:
          - is_left
          - is_right
      bumper_light_sensors_bool:
        - interfaces:
          - is_light_left
          - is_light_front_left
          - is_light_center_left
          - is_light_center_right
          - is_light_front_right
          - is_light_right
      bumper_light_sensors_raw:
        - interfaces:
          - light_left
          - light_front_left
          - light_center_left
          - light_center_right
          - light_front_right
          - light_right
      battery:
        - interfaces:
          - capacity
          - charge
          - state
          - voltage
          - current
          - temperature
      cliff:
        - interfaces:
          - left
          - front_left
          - right 
          - front_right
      wheeldrop:
        - interfaces:
          - left
          - right 
