name: Build robotics infrastructure

# Trigger this workflow on pushes to any branch and tags matching v*.*.*
on:
  push:
    branches: [ '*' ]
    tags: [ 'v*.*.*' ]

jobs:
  # build generic ROS2 container
  build_ros2_base:
    uses: amidg/workflows/.github/workflows/build_docker_multiarch.yml@main
    with:
      container_name: ros2
      container_file: containers/Containerfile
      container_tag:  ${{ github.sha }}
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}
