name: Build robotics infrastructure

# Trigger this workflow on pushes to any branch and tags matching v*.*.*
on:
  push:
    branches: [ '*' ]
    tags: [ 'v*.*.*' ]

jobs:
  # build generic ROS2 container
  build_ros2_base:
    uses: amidg/workflows/.github/workflows/build_docker_multiarch.yml@main
    with:
      container_name: ros2
      container_file: containers/Containerfile
      container_tag:  ${{ github.sha }}
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

  # build controls contains two jobs:
  # - runtime (deployment)
  # - dev image
  build_controls:
    needs:
      - build_ros2_base
    uses: amidg/workflows/.github/workflows/build_docker_multiarch.yml@main
    strategy:
      matrix:
        include:
          - container_name: ros2_controls_runtime
            build_target: runtime
          - container_name: ros2_controls_dev
            build_target: dev
    with:
      container_name: ${{ matrix.container_name }}
      container_file: runtimes/Containerfile
      container_tag: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
      build_target: ${{ matrix.build_target }}
      build_args: |
        GITHUB_SHA=${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
        RUNTIME=controls
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

